version: "3.9"

services:
  app:
    build: .
    container_name: technova-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=technova_inventory
      - DB_TEST_NAME=technova_inventory_test
      - CI_ENVIRONMENT=production
    volumes:
      - ./writable:/var/www/html/writable
    networks:
      - technova-net

  webserver:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: technova-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - technova-net

  db:
    image: mysql:8.0
    container_name: technova-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: technova_inventory
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - technova-net

volumes:
  db-data:

networks:
  technova-net:
    driver: bridge